version: '2.12.0'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_analysis
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
            - 27017:27017